### ISSUE TITLE
Dynamic definition and evaluation of states machine

### ISSUE THREAD

**Issue by daya** [entropealabs/states_language#9]
Using something like States Language editor and resulting json output, is it possible to dynamically (at runtime) define state machines and have the state machine executed/evaluated?

**Comment by entone** [comment]
Yes, it is. I would need a bit more details on your use-case to provide an
ideal path forward.

My use-case in the past was that the state machines were pre-defined, but
you could update the JSON itself backing the state machine and use hot code
reloading to update the gen_statem module.

**Comment by daya** [comment]
Thanks for the reply @entone my use case is a logged in User using some Editor (like states-language editor) is able to define a State machine with all the steps, branching logic and callouts (webhooks). The system/application will then run one or more executions of this user defined state machine and generate report on them.

Obviously as you can make out there will be a Schema based on the business domain which will control the possible state machines that can be generated.   

Do you think this kind of runtime creation and execution of state machines is easy enough to implement states_language? or will it require too much arm twisting?

**Comment by entone** [comment]
Not at all, I think it is quite doable. My approach has been to create a
Macro that will define the StatesLanguage implementation, the macro should
accept the JSON file or Map structure and generate a module at runtime, you
can then start a process based on the compiled module.

I have implemented something very similar for an IVR system, the original
inspiration for the project, however I'm not able to share that code.

It will come down to using something along the lines of
https://hexdocs.pm/elixir/Code.html#compile_string/2 to compile the module,
and starting that as a Task or under a supervision tree.

**Comment by daya** [comment]
> the macro should accept the JSON file or Map structure and generate a module at runtime, you
can then start a process based on the compiled module.

Right that's one high level interface to the internals, and I hope you meant something along these lines, right?

```elixir
defmodule MyModule do

use StatesLanguage, data: %{state1: %{}, state2: %{}} 

end
``` 
but as that is compile time still, I am looking for some place in code base where that compile time configuration is executed to interpret the graph into a `gen_statem` process. Could you please help me with a pointer to that module/line?

**Comment by entone** [comment]
You will need to use Code.compile_string in order to do it at runtime, or
another one of the functions that will compile a module, and pass in the
data by either writing the JSON to a file, or using something like
Code.compile_quoted to pass in a map to your macro.
